[project]
name = "sayantankhan-io"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "markdown>=3.7",
    "pelican>=4.11.0",
    "pelican-render-math>=1.0.4",
]
